l2chains = [{name = "Worldchain Sepolia", chainId = 4801}]
templateName = "TransferL2PAOFromL1ToEOA"

# The new owner address (EOA). See here https://www.notion.so/oplabs/Worldchain-key-handback-over-address-validation-272f153ee1628002bfa2e00a718c57d5?source=copy_link
newOwnerEOA = "0xe78a0A96C5D6aE6C606418ED4A9Ced378cb030A0"

[addresses]
ProxyAdminOwner = "0x1Eb2fFc903729a0F03966B917003800b145F56E2"

[stateOverrides]
# ProxyAdminOwner
0x1Eb2fFc903729a0F03966B917003800b145F56E2 = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 44}
]

# Foundation Upgrades Safe
0xDEe57160aAfCF04c34C887B5962D0a69676d3C8B = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 62}
]

# Security Council
0xf64bc17485f0B4Ea5F06A96514182FC4cB561977 = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 57}
]
