l2chains = [
    {name = "arena-z-testnet", chainId = 9899}
]

templateName = "OPCMUpgradeV500"

allowOverwrite = ["SuperchainConfig"]



# Arena-Z Testnet (Permissioned)

[[opcmUpgrades]]
chainId = 9899
absolutePrestate = "0x038dca684026d946d1d0ddb05d50685d1a0dab350b89d10b6705e83c41ec8755"  # prestates."1.7.0-rc.5" https://github.com/ethereum-optimism/devnets/issues/123#issuecomment-3444735369
expectedValidationErrors = "PDDG-VM-30,PLDG-10"



[addresses]

OPCM = "0x6af7ece7d6506be573841b8cf29096638df5fc4f"  # Source: https://www.notion.so/oplabs/op-contracts-release-for-U17-Jovian-294f153ee16280b99539c5b6de67c72f?source=copy_link#295f153ee162800a84c7f37811ecf3ec
StandardValidatorV500 = "0x8ed9A48B40675acf9ec623aFc23DdB015Ae60df0"  # Source: cast call validator's from OPCM above
SuperchainConfig = "0xC2Be75506d5724086DEB7245bd260Cc9753911Be"  # Source: https://github.com/ethereum-optimism/superchain-registry/blob/6748f8050bfab9930abdfc46288f9629af2f7b38/superchain/configs/sepolia/superchain.toml#L3C27-L3C69
SuperchainConfigProxyAdmin = "0x189aBAAaa82DfC015A588A7dbaD6F13b1D3485Bc"  # Source: cast call ProxyAdmin address from SuperchainConfig above


[stateOverrides]

0x1Eb2fFc903729a0F03966B917003800b145F56E2 = [ # L1PAO
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 40}
]
0xf64bc17485f0B4Ea5F06A96514182FC4cB561977 = [ # SC
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 52}
]
0xDEe57160aAfCF04c34C887B5962D0a69676d3C8B = [ # FUS
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 55}
]