templateName = "AddGameTypeTemplate"
fallbackAddressesJsonPath = "src/tasks/sep/050-op-betanet-add-game-type/addresses.json"

l2chains = [    
    {name = "u18-beta-1", chainId = 420110022},
]

[[configs]]
# The below addresses can be found here https://github.com/ethereum-optimism/devnets/blob/main/betanets/u18-beta/u18-beta-1/chain.yaml
chainId = 420110022
saltMixer = "this is a salt mixer"
systemConfig = "0x5babF93aC7AFfeaE25dc1a7ad4587fDeEbba44C2"
proxyAdmin = "0xcd18a0C04286Eba52Bb168Fa1D79133Da4856bEf"
delayedWETH = "0x62841F5E03a56f818BC8818c5130757acA2541A7"
disputeGameType = 0
disputeAbsolutePrestate = "0x03ccb5619628eeba89d58b204aadeb2ed9f51d18ff938069dd298b9e19fb2d31" # Source: https://www.notion.so/oplabs/Betanet-2a9f153ee16280859261e3000d866ee9?source=copy_link#2c5f153ee1628012bc4dfbeaae710c70
disputeMaxGameDepth = 73
disputeSplitDepth = 30
disputeClockExtension = 10800
disputeMaxClockDuration = 302400
initialBond = 80000000000000000
vm = "0x6463dEE3828677F6270d83d45408044fc5eDB908" # Source: https://github.com/ethereum-optimism/superchain-registry/blob/ad5becd08007b80988679b8f0c08d415e1294066/validation/standard/standard-versions-sepolia.toml#L11
permissioned = false

[addresses]
OPCM = "0xc69e4c24db479191676611a25d977203c3bdca62" # https://github.com/ethereum-optimism/superchain-registry/blob/74d9bb4ad4cd8d6fd453f2e9dfe5380d97c07ca9/validation/standard/standard-versions-sepolia.toml#L23C56-L23C98

[stateOverrides]
0xe934Dc97E347C6aCef74364B50125bb8689c40ff = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 55}
]
