l2chains = [
  {name = "Soneium Testnet Minato", chainId = 1946}
]

templateName = "SetRespectedGameTypeTemplate"

[gameTypes]
configs = [
  {chainId = 1946, gameType = 0}
]

[stateOverrides]
# ProxyAdminOwner
0x1Eb2fFc903729a0F03966B917003800b145F56E2 = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 46}
]

# Security Council
0xf64bc17485f0B4Ea5F06A96514182FC4cB561977 = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 59}
]
