l2chains = [    
    {name = "OP Sepolia Testnet", chainId = 11155420},
    {name = "Ink Sepolia Testnet", chainId = 763373}
]

templateName = "OPCMUpgradeV400"

# OP Sepolia Testnet
[[opcmUpgrades]]
chainId = 11155420
# prestates."1.6.1-rc.1
# https://github.com/ethereum-optimism/superchain-registry/blob/d82a61168fd1d7ef522ed8e213ce23c853031495/validation/standard/standard-prestates.toml#L6
absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc8"
expectedValidationErrors = ""

# Ink Sepolia Testnet
[[opcmUpgrades]]
chainId = 763373
# prestates."1.6.1-rc.1
# https://github.com/ethereum-optimism/superchain-registry/blob/d82a61168fd1d7ef522ed8e213ce23c853031495/validation/standard/standard-prestates.toml#L6

absolutePrestate = "0x03eb07101fbdeaf3f04d9fb76526362c1eea2824e4c6e970bdb19675b72e4fc8"
expectedValidationErrors = ""

[addresses]
OPCM = "0x44c191ce5ce35131e703532af75fa9ca221e2398" # Freshly deployed on Sepolia
StandardValidatorV400 = "0x482160a136b7aA13d05441cDB6f09a61AF36b935" # Freshly deployed on Sepolia