# RevShare Betanet on U18
l2chains = [
    {name = "revshare-beta-0", chainId = 420120033}
]

# Addresses: https://github.com/ethereum-optimism/devnets/tree/main/betanets/revshare-beta

fallbackAddressesJsonPath = "src/tasks/sep/060-U18-rev-share-betanet/addresses.json"

templateName = "OPCMUpgradeV600"

[[opcmUpgrades]]
chainId = 420120033
# U18 prestates for betanet: https://www.notion.so/oplabs/Betanet-2a9f153ee16280859261e3000d866ee9
cannonPrestate = "0x0364251d4ea4b677ac462a25642b6de1fa53b2d6b97e56380691906bdb2e95cf"
cannonKonaPrestate = "0x03091ea717990785736623f894e6fb344fcf262361657bb28c9ece29207d9a9c"
expectedValidationErrors = "OVERRIDES-L1PAOMULTISIG,OVERRIDES-CHALLENGER,SYSCON-130"
# OVERRIDES-L1PAOMULTISIG,OVERRIDES-CHALLENGER: not the standard OP Sepolia ones
# SYSCON-130: SystemConfig proxyAdmin on betanets is not the standard OP Sepolia one

[addresses]
OPCM = "0xf0a2e224519e876979ea6b2cd15ef5cc3d6703bd"  # v600 OPCM

[stateOverrides]
0xf64bc17485f0B4Ea5F06A96514182FC4cB561977 = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 63}
]
