[tools]

# Core dependencies
go = "1.24.6"
just = "1.37.0"
shellcheck = "0.10.0"
yq = "4.44.5"
fzf = "0.65.0"

# Foundry dependencies
# Foundry is a special case because it supplies multiple binaries at the same
# GitHub release, so we need to use the aliasing trick to get mise to not error
# The git ref here should be on the `stable` branch.
# WARNING: DO NOT CHANGE FORGE/CAST/ANVIL VERSIONS UNLESS ABSOLUTELY NECESSARY!
# https://github.com/foundry-rs/foundry/releases/tag/v1.2.3
forge = "v1.2.3"
cast = "v1.2.3"
anvil = "v1.2.3"

[alias]
forge = "ubi:foundry-rs/foundry[exe=forge]"
cast = "ubi:foundry-rs/foundry[exe=cast]"
anvil = "ubi:foundry-rs/foundry[exe=anvil]"
fzf = "ubi:junegunn/fzf"
