templateName = "MigrateToLiveness2"

safeAddressString = "FoundationUpgradeSafe"

[addresses]
saferSafes = "0xA8447329e52F64AED2bFc9E7a2506F7D369f483a"
# currentLivenessModule is omitted - FuS has no existing liveness module

[livenessModule]
livenessResponsePeriod = "2592000"  # 30 days in seconds
fallbackOwner = "0xc2819DC788505Aac350142A7A707BF9D03E3Bd03"  # Security Council

[stateOverrides]
# Foundation Upgrade Safe
0x847B5c174615B1B7fDF770882256e2D3E95b9D92 = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 48}
]

