l2chains = [
    {name = "OP Sepolia Testnet", chainId = 11155420}, 
    {name = "Soneium Testnet Minato", chainId = 1946},
    {name = "Ink Sepolia", chainId = 763373}
]

templateName = "OPCMUpgradeV300"

[opcmUpgrades]
absolutePrestates = [
    {absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405", chainId = 11155420}, 
    {absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405", chainId = 1946}, 
    {absolutePrestate = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405", chainId = 763373}
]

[addresses]
OPCM = "0xfbceed4de885645fbded164910e10f52febfab35"
StandardValidatorV300 = "0xd0d7f75561bb7105db2d34dc39b31f23578fb75b"
FoundationUpgradeSafe = "0xDEe57160aAfCF04c34C887B5962D0a69676d3C8B" # Owner on the proxy admin owner
SecurityCouncil = "0xf64bc17485f0B4Ea5F06A96514182FC4cB561977" # Owner on the proxy admin owner
