l2chains = [
    {name = "Unichain Sepolia Testnet", chainId = 1301}
]

templateName = "OPCMUpgradeV200"

[opcmUpgrades]
absolutePrestates = [
    {absolutePrestate = "0x0354eee87a1775d96afee8977ef6d5d6bd3612b256170952a01bf1051610ee01", chainId = 1301},
]

[addresses]
OPCM = "0x1B25F566336F47BC5E0036D66E142237DcF4640b"
StandardValidatorV200 = "0x37739a6b0a3F1E7429499a4eC4A0685439Daff5C"
