# RevShare Upgrade and Setup Configuration

templateName = "RevShareUpgradeAndSetup"

# L2 chains to target
l2chains = [
  {name = "Soneium Testnet Minato", chainId = 1946}
]

safeAddress = "ProxyAdminOwner"

# RevShareContractsUpgrader address
# https://sepolia.etherscan.io/address/0x71241bbae674967dD523e621c272Ea32cf33119A
revShareUpgrader = "0x71241bbae674967dD523e621c272Ea32cf33119A"

# RevShare configurations (one per chain) - flattened arrays
# https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/sepolia/soneium-minato.toml#L50
portals = [
  "0x65ea1489741A5D72fFdD8e6485B216bBdcC15Af3"  # Soneium Testnet Minato Portal
]

chainFeesRecipients = [
  "0x660203DD7E933646905DfDc2C3c0Bb156d51000A"
]

# 2 ether
l1WithdrawerMinWithdrawalAmounts = [2000000000000000000]

# FeesDepositor address in sepolia
l1WithdrawerRecipients = [
  "0xed9B99a703BaD32AC96FDdc313c0652e379251Fd"
]
l1WithdrawerGasLimits = [800000]

[addresses]
https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/sepolia/soneium-minato.toml#L46
ProxyAdminOwner = "0x1Eb2fFc903729a0F03966B917003800b145F56E2"

[stateOverrides]
0x1Eb2fFc903729a0F03966B917003800b145F56E2 = [ # L1PAO
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 48}
]
0xf64bc17485f0B4Ea5F06A96514182FC4cB561977 = [ # SC
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 62}
]
0xDEe57160aAfCF04c34C887B5962D0a69676d3C8B = [ # FUS
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 67}
]

