# RevShare Upgrade And Setup Configuration

templateName = "RevShareUpgradeAndSetup"

# L2 chains to target
l2chains = [{name = "revshare-beta-0", chainId = 420120033}]

safeAddress = "ProxyAdminOwner"

# RevShareContractsUpgrader address
revShareUpgrader = "0x71241bbae674967dd523e621c272ea32cf33119a" 

# RevShare configurations (one per chain) - flattened arrays
portals = ["0xa1F4F424901e0773e68C714077bCDD5CF8BcEc23"]

chainFeesRecipients = ["0x5f077b4c3509C2c192e50B6654d924Fcb8126A60"]

# 2 ether
l1WithdrawerMinWithdrawalAmounts = [2000000000000000000]

# FeesDepositor address in mainnet
l1WithdrawerRecipients = ["0xed9B99a703BaD32AC96FDdc313c0652e379251Fd"]
l1WithdrawerGasLimits = [800000]

fallbackAddressesJsonPath = "src/tasks/sep/060-betanet-rev-share/addresses.json"

[addresses]
ProxyAdminOwner = "0x1eb2ffc903729a0f03966b917003800b145f56e2"

[stateOverrides]
0x1Eb2fFc903729a0F03966B917003800b145F56E2 = [ # L1PAO
{key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 47}
]
0xf64bc17485f0B4Ea5F06A96514182FC4cB561977 = [ # SC
{key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 61}
]
0xDEe57160aAfCF04c34C887B5962D0a69676d3C8B = [ # FUS
{key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 66}
]