# RevShare Upgrade And Setup Configuration

templateName = "RevShareUpgradeAndSetup"

# L2 chains to target
l2chains = [{name = "revshare-beta-0", chainId = 420120033}]

safeAddress = "ProxyAdminOwner"

# RevShareContractsUpgrader address
revShareUpgrader = "0x71241bbae674967dd523e621c272ea32cf33119a"

# RevShare configurations (one per chain) - flattened arrays
portals = ["0xa1F4F424901e0773e68C714077bCDD5CF8BcEc23"]

chainFeesRecipients = ["0x5f077b4c3509C2c192e50B6654d924Fcb8126A60"]

# 2 ether
l1WithdrawerMinWithdrawalAmounts = [2000000000000000000]

# FeesDepositor address
l1WithdrawerRecipients = ["0xed9B99a703BaD32AC96FDdc313c0652e379251Fd"]
l1WithdrawerGasLimits = [800000]

fallbackAddressesJsonPath = "src/tasks/sep/061-betanet-rev-share/addresses.json"

[addresses]
ProxyAdminOwner = "0xe934Dc97E347C6aCef74364B50125bb8689c40ff"

[stateOverrides]
0xe934Dc97E347C6aCef74364B50125bb8689c40ff = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 67}
]