templateName = "GnosisSafeRotateSigner"

safeAddressString = "FoundationUpgradeSafe"

# Pete is an owner on the Sepolia Foundation Upgrade Safe: 0xDEe57160aAfCF04c34C887B5962D0a69676d3C8B.
ownerToRemove = "0x72e828fdB48Cac259CB60d03222774fBD7e5522C"
ownerToAdd = "0xC703d73DB3804662B81b260056d8518Ab54e984E"

[stateOverrides]
0xDEe57160aAfCF04c34C887B5962D0a69676d3C8B = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 69}
]
