l2chains = [
    {name = "Base Sepolia Testnet", chainId = 84532}
]

templateName = "OPCMUpgradeV500"

allowOverwrite = ["SuperchainConfig"]



# Base Sepolia Testnet (Permissionless)

[[opcmUpgrades]]
chainId = 84532
absolutePrestate = "0x038dca684026d946d1d0ddb05d50685d1a0dab350b89d10b6705e83c41ec8755"  # prestates."1.7.0-rc.5" https://github.com/ethereum-optimism/devnets/issues/123#issuecomment-3444735369
expectedValidationErrors = "PROXYA-10,DF-30,PDDG-DWETH-30,PDDG-VM-30,PDDG-130,PLDG-DWETH-30,PLDG-VM-30"



[addresses]

OPCM = "0x6af7ece7d6506be573841b8cf29096638df5fc4f"  # Source: https://www.notion.so/oplabs/op-contracts-release-for-U17-Jovian-294f153ee16280b99539c5b6de67c72f?source=copy_link#295f153ee162800a84c7f37811ecf3ec
StandardValidatorV500 = "0x8ed9A48B40675acf9ec623aFc23DdB015Ae60df0"  # Source: cast call validator's from OPCM above
SuperchainConfig = "0xC2Be75506d5724086DEB7245bd260Cc9753911Be"  # Source: https://github.com/ethereum-optimism/superchain-registry/blob/6748f8050bfab9930abdfc46288f9629af2f7b38/superchain/configs/sepolia/superchain.toml#L3C27-L3C69
SuperchainConfigProxyAdmin = "0x189aBAAaa82DfC015A588A7dbaD6F13b1D3485Bc"  # Source: cast call ProxyAdmin address from SuperchainConfig above


[stateOverrides]

# Base Sepolia ProxyAdminOwner
0x0fe884546476dDd290eC46318785046ef68a0BA9 = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 26}
]

# Base Nested Safe
0x646132A1667ca7aD00d36616AFBA1A28116C770A = [ 
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 9}
]

# Base Council Safe
0x5dfEB066334B67355A15dc9b67317fD2a2e1f77f = [ 
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 10}
]

# Base Operations Safe
0x6AF0674791925f767060Dd52f7fB20984E8639d8 = [ 
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 14} # <--- THIS MUST BE CHANGED TO '15' FOR STEP 1A IN README.md FILE.
]
