l2chains = [
    {name = "Base", chainId = 8453}
]

templateName = "OPCMUpgradeV500"

allowOverwrite = ["SuperchainConfig"]



# Base (Permissionless)

[[opcmUpgrades]]
chainId = 8453
absolutePrestate = "0x038dca684026d946d1d0ddb05d50685d1a0dab350b89d10b6705e83c41ec8755"  # prestates."1.7.0-rc.5" https://github.com/ethereum-optimism/devnets/issues/123#issuecomment-3444735369
expectedValidationErrors = "PDDG-VM-30,PLDG-VM-30"



[addresses]

OPCM = "0x9e86a129e86a570fb13e89bd5e9aa98b642ae4c5" # Source: https://www.notion.so/oplabs/op-contracts-release-for-U17-Jovian-294f153ee16280b99539c5b6de67c72f?source=copy_link#295f153ee16280fe9c9af13970a5fac6
StandardValidatorV500 = "0xE0b673cB5Da8DaC181d4D712eA563c4B14230286" # Source: cast call validator's from OPCM above
SuperchainConfig = "0x95703e0982140D16f8ebA6d158FccEde42f04a4C" # Source: https://github.com/ethereum-optimism/superchain-registry/blob/6748f8050bfab9930abdfc46288f9629af2f7b38/superchain/configs/mainnet/superchain.toml#L3C27-L3C69
SuperchainConfigProxyAdmin = "0x543bA4AADBAb8f9025686Bd03993043599c6fB04" # Source: cast call ProxyAdmin address from SuperchainConfig above


[stateOverrides]

# Base Mainnet ProxyAdminOwner
0x7bB41C3008B3f03FE483B28b8DB90e19Cf07595c = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 10}
]

# Base Nested Safe
0x9855054731540A48b28990B63DcF4f33d8AE46A1 = [ 
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 23}
]

# Base Council Safe
0x20AcF55A3DCfe07fC4cecaCFa1628F788EC8A4Dd = [ 
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 2}
]

# Base Operations Safe
0x9C4a57Feb77e294Fd7BF5EBE9AB01CAA0a90A110 = [ 
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 3}
]

# Foundation Operation Safe
0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A = [ 
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 109}
]