# RevShare Upgrade and Setup Configuration

templateName = "RevShareUpgradeAndSetup"

# L2 chains to target
l2chains = [
  {name = "Ink Sepolia", chainId = 763373}
]

safeAddress = "ProxyAdminOwner"

# RevShareContractsUpgrader address
# https://sepolia.etherscan.io/address/0x71241bbae674967dD523e621c272Ea32cf33119A
revShareUpgrader = "0x71241bbae674967dD523e621c272Ea32cf33119A"

# RevShare configurations (one per chain) - flattened arrays
https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/sepolia/ink.toml#L50
portals = [
  "0x5c1d29C6c9C8b0800692acC95D700bcb4966A1d7" # Ink Sepolia Portal
]

chainFeesRecipients = [
  "0xBeA2Bc852a160B8547273660E22F4F08C2fa9Bbb",
]

# 2 ether
l1WithdrawerMinWithdrawalAmounts = [2000000000000000000]

# FeesDepositor address in sepolia
l1WithdrawerRecipients = [
  "0xed9B99a703BaD32AC96FDdc313c0652e379251Fd",
]
l1WithdrawerGasLimits = [800000]

[addresses]
https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/sepolia/ink.toml#L46
ProxyAdminOwner = "0x1Eb2fFc903729a0F03966B917003800b145F56E2"

[stateOverrides]
0x1Eb2fFc903729a0F03966B917003800b145F56E2 = [ # L1PAO
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 47}
]
0xf64bc17485f0B4Ea5F06A96514182FC4cB561977 = [ # SC
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 61}
]
0xDEe57160aAfCF04c34C887B5962D0a69676d3C8B = [ # FUS
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 66}
]

