# U18 Sepolia networks (OP, Ink, Metal, Mode, Zora, Arena-z)
l2chains = [
    {name = "OP Sepolia Testnet", chainId = 11155420},
    {name = "Ink Sepolia Testnet", chainId = 763373},
    {name = "Metal L2 Testnet", chainId = 1740},
    {name = "Mode Testnet", chainId = 919},
    {name = "Zora Sepolia Testnet", chainId = 999999999},
    {name = "arena-z-testnet", chainId = 9899}
]


templateName = "OPCMUpgradeV600"
# U18 prestates: 


# OP Sepolia Testnet (Permissionless)
[[opcmUpgrades]]
chainId = 11155420
cannonPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead" 
cannonKonaPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead"
expectedValidationErrors = ""

# Ink Sepolia Testnet (Permissionless)
[[opcmUpgrades]]
chainId = 763373
cannonPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead" 
cannonKonaPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead"
expectedValidationErrors = ""

# Metal L2 Testnet (Permissioned)
[[opcmUpgrades]]
chainId = 1740
cannonPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead" 
cannonKonaPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead"
expectedValidationErrors = "PLDG-10,CKDG-10"
# PLDG-10: this is expected because u18-beta-0 is a Permissioned chain
# CKDG-10: Custom dispute game implementation not found, expected as it's a Permissioned chain with no Permissionless implementation

# Mode Testnet (Permissioned)
[[opcmUpgrades]]
chainId = 919
cannonPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead" 
cannonKonaPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead"
expectedValidationErrors = "PLDG-10,CKDG-10"
# PLDG-10: this is expected because u18-beta-0 is a Permissioned chain
# CKDG-10: Custom dispute game implementation not found, expected as it's a Permissioned chain with no Permissionless implementation

# Zora Sepolia Testnet (Permissioned)
[[opcmUpgrades]]
chainId = 999999999
cannonPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead" 
cannonKonaPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead"
expectedValidationErrors = "PLDG-10,CKDG-10"
# PLDG-10: this is expected because u18-beta-0 is a Permissioned chain
# CKDG-10: Custom dispute game implementation not found, expected as it's a Permissioned chain with no Permissionless implementation

# Arena-Z Testnet (Permissioned)
[[opcmUpgrades]]
chainId = 9899
cannonPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead" 
cannonKonaPrestate = "0xdeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddeaddead"
expectedValidationErrors = "PLDG-10,CKDG-10"
# PLDG-10: this is expected because u18-beta-0 is a Permissioned chain
# CKDG-10: Custom dispute game implementation not found, expected as it's a Permissioned chain with no Permissionless implementation


[addresses]
OPCM = "0xf0a2e224519e876979ea6b2cd15ef5cc3d6703bd"  # v600 OPCM source: https://github.com/ethereum-optimism/superchain-registry/blob/c84ed822ae5a65500d8c0e323460fa688cfcca22/validation/standard/standard-versions-sepolia.toml#L23C56-L23C98


[stateOverrides]
0x1Eb2fFc903729a0F03966B917003800b145F56E2 = [ # L1PAO
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 47}
]
0xf64bc17485f0B4Ea5F06A96514182FC4cB561977 = [ # SC
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 61}
]
0xDEe57160aAfCF04c34C887B5962D0a69676d3C8B = [ # FUS
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 65}
]
