# this is the file used to determine the network configuration
templateName = "EnableDeputyPauseModuleTemplate"

newModule = "0xc10dac07d477215a1ebebae1dd0221c1f5d241d2"
safeAddressString = "GuardianSafe"
foundationSafeString = "FoundationUpgradeSafe"
deputyPauseModuleVersion = "2.1.0"

[stateOverrides]

0xf64bc17485f0B4Ea5F06A96514182FC4cB561977 = [ # Security Council
  {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 39}
]
