templateName = "MigrateToLiveness2"

safeAddressString = "FoundationOperationsSafe"

[addresses]
saferSafes = "0xA8447329e52F64AED2bFc9E7a2506F7D369f483a"
# currentLivenessModule is omitted - FoS has no existing liveness module

[livenessModule]
livenessResponsePeriod = "2592000"  # 30 days in seconds
fallbackOwner = "0xf64bc17485f0B4Ea5F06A96514182FC4cB561977"  # Security Council

[stateOverrides]
# Foundation Operations Safe
0x837DE453AD5F21E89771e3c06239d8236c0EFd5E = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 10}
]

