templateName = "GnosisSafeRotateSigner"

safeAddressString = "FoundationOperationsSafe"

ownerToRemove = "0x69acfE2096Dfb8d5A041eF37693553c48d9BFd02"
ownerToAdd = "0xc222ab08333109243B1f4E2a80e3D0A190714AB5"

[stateOverrides]

0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 115}
]
