# Freya Devnet on u15
l2chains = [
    {name = "u18-beta-1", chainId = 420110022},
]

fallbackAddressesJsonPath = "src/tasks/sep/051-U18-op-betanet-superchainconfig/addresses.json"
templateName = "OPCMUpgradeSuperchainConfigV600"

allowOverwrite = ["SuperchainConfig"]

[addresses]
# Source for the addresses below: https://github.com/ethereum-optimism/devnets/blob/main/betanets/u18-beta/u18-beta-1/chain.yaml
OPCM = "0x60FD34b4652a4126932D5f14bf995BA9f8C2899F"
StandardValidatorV600 = "0xA3d0BfF9B7ccE767A36D82881B89fBEF1f14EABB"
SuperchainConfig = "0xBC64837fbFC57946F11a4148EBa89C48812c8dF4"
SuperchainConfigProxyAdmin = "0x0D6A1A07193B222C938C568b0B9A3C691C809760"

[stateOverrides]
0xe934Dc97E347C6aCef74364B50125bb8689c40ff = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 57}
]