templateName = "AddGameTypeTemplate"
fallbackAddressesJsonPath = "src/tasks/sep/047-op-betanet-add-game-type/addresses.json"

l2chains = [    
    {name = "u18-beta-1", chainId = 420110022},
]

[[configs]]
# The below addresses can be found in the Superchain Registry https://github.com/ethereum-optimism/superchain-registry/blob/851f7bb60edc53373fc961d237c7175aa130fba3/superchain/extra/addresses/addresses.json#L402
chainId = 420110022
saltMixer = "this is a salt mixer"
systemConfig = "0xe934Dc97E347C6aCef74364B50125bb8689c40ff"
proxyAdmin = "0xcd18a0C04286Eba52Bb168Fa1D79133Da4856bEf"
delayedWETH = "0x62841F5E03a56f818BC8818c5130757acA2541A7"
disputeGameType = 0
disputeAbsolutePrestate = "0x0339db503776757491b9f3038bf6f1d37b7988a2f75e823fe2656c1352ef2f91" # Absolute Prestate 1.7.0-rc.3 https://github.com/ethereum-optimism/superchain-registry/blob/851f7bb60edc53373fc961d237c7175aa130fba3/validation/standard/standard-prestates.toml#L6
disputeMaxGameDepth = 73
disputeSplitDepth = 30
disputeClockExtension = 10800
disputeMaxClockDuration = 302400
initialBond = 80000000000000000
vm = "0x6463dEE3828677F6270d83d45408044fc5eDB908"
permissioned = false

[addresses]
OPCM = "0x60FD34b4652a4126932D5f14bf995BA9f8C2899F"

[stateOverrides]
0xe934Dc97E347C6aCef74364B50125bb8689c40ff = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 36}
]
