l2chains = [
    {name = "Unichain Sepolia Testnet", chainId = 1301}
]

templateName = "OPCMUpgradeV500"

allowOverwrite = ["SuperchainConfig"]



# Unichain Sepolia Testnet (Permissionless)

[[opcmUpgrades]]
chainId = 1301
absolutePrestate = "0x03799051d2bfe459127d4597f469f535ff1bd2a6e1e2134443167620871c11f3"  # prestates."1.8.0-rc.3" https://github.com/ethereum-optimism/superchain-registry/blob/c9881d543174ff00b8f3a9ad3f31bf4630b9743b/validation/standard/standard-prestates.toml#L6
expectedValidationErrors = "PROXYA-10,DF-30,PDDG-DWETH-30,PDDG-130,PLDG-DWETH-30"



[addresses]

OPCM = "0x6af7ece7d6506be573841b8cf29096638df5fc4f"  # Source: https://www.notion.so/oplabs/op-contracts-release-for-U17-Jovian-294f153ee16280b99539c5b6de67c72f?source=copy_link#295f153ee162800a84c7f37811ecf3ec
StandardValidatorV500 = "0x8ed9A48B40675acf9ec623aFc23DdB015Ae60df0"  # Source: cast call validator's from OPCM above
SuperchainConfig = "0xC2Be75506d5724086DEB7245bd260Cc9753911Be"  # Source: https://github.com/ethereum-optimism/superchain-registry/blob/6748f8050bfab9930abdfc46288f9629af2f7b38/superchain/configs/sepolia/superchain.toml#L3C27-L3C69
SuperchainConfigProxyAdmin = "0x189aBAAaa82DfC015A588A7dbaD6F13b1D3485Bc"  # Source: cast call ProxyAdmin address from SuperchainConfig above


[stateOverrides]

# Unichain Sepolia ProxyAdminOwner:
0xd363339eE47775888Df411A163c586a8BdEA9dbf = [ # L1PAO
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 40}
]
