templateName = "GnosisSafeRotateMultipleSigners"

safeAddressString = "FoundationOperationsSafe"

ownersToRemove = [
    "0x0000000000000000000000000000000000000000",
    "0x0000000000000000000000000000000000000000"
]

ownersToAdd = [
    "0xAAAA000000000000000000000000000000000001",
    "0xBBBB000000000000000000000000000000000002"
]

[stateOverrides]
# Nonce override for simulation (storage slot 0x5 is the nonce)
0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 115}
]
