# U18 Soneium Mainnet
l2chains = [
    {name = "Soneium", chainId = 1868}
]


templateName = "OPCMUpgradeV600"


# Soneium Mainnet (Permissioned)
[[opcmUpgrades]]
chainId = 1868
# U18 prestates: https://www.notion.so/oplabs/Upgrade-18-Governance-Post-2d1f153ee162807db0deee6100c9ad5a?source=copy_link#2d1f153ee16280b197bcf82b759ad1d6
cannonPrestate = "0x033c000916b4a88cfffeceddd6cf0f4be3897a89195941e5a7c3f8209b4dbb6e" 
cannonKonaPrestate = "0x0323914d3050e80c3d09da528be54794fde60cd26849cd3410dde0da7cd7d4fa"
expectedValidationErrors = "PLDG-10,CKDG-10"
# PLDG-10: CANNON game type not found, expected as it's a Permissioned chain
# CKDG-10: CANNON_KONA game type not found, expected as it's a Permissioned chain


[addresses]
OPCM = "0x50f47b43c24f40b92c873fa0704d4207586d0c9f"  # v600 OPCM source: https://github.com/ethereum-optimism/superchain-registry/blob/c84ed822ae5a65500d8c0e323460fa688cfcca22/validation/standard/standard-versions-mainnet.toml#L23


[stateOverrides]
# ProxyAdminOwner
0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 32}
]
# Foundation Upgrades Safe
0x847B5c174615B1B7fDF770882256e2D3E95b9D92 = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 50}
]
# Security Council
0xc2819DC788505Aac350142A7A707BF9D03E3Bd03 = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 52}
]
