# RevShare Upgrade And Setup Configuration

templateName = "RevShareUpgradeAndSetup"

# L2 chains to target
l2chains = [{name = "revshare-beta-0", chainId = 420120033}]

safeAddress = "ProxyAdminOwner"

# RevShareContractsUpgrader https://sepolia.etherscan.io/address/0x71241bbae674967dd523e621c272ea32cf33119a
revShareUpgrader = "0x71241bbae674967dd523e621c272ea32cf33119a"

# RevShare configurations (one per chain)
# Betanet Portal in Sepolia https://sepolia.etherscan.io/address/0x4fC40f2D8cf14925567938d209EB493a43347A79
# Source https://github.com/ethereum-optimism/devnets/blob/f3c0a223a99bb0aaa6c2a5c9e57cc112f3beb9eb/betanets/revshare-beta/revshare-beta-0/chain.yaml#L14
portals = ["0x4fC40f2D8cf14925567938d209EB493a43347A79"]

# SequencerFeeVault.RECIPIENT() in the betanet.
chainFeesRecipients = ["0x7e31e1EafB4D1486C05743e5C496cB5042843d7a"] 

# 2 ether
l1WithdrawerMinWithdrawalAmounts = [2000000000000000000]

# FeesDepositor https://sepolia.etherscan.io/address/0xed9B99a703BaD32AC96FDdc313c0652e379251Fd
l1WithdrawerRecipients = ["0xed9B99a703BaD32AC96FDdc313c0652e379251Fd"]
l1WithdrawerGasLimits = [800000]

fallbackAddressesJsonPath = "src/tasks/sep/062-betanet-rev-share-v2/addresses.json"

[addresses]
ProxyAdminOwner = "0xe934Dc97E347C6aCef74364B50125bb8689c40ff"

[stateOverrides]
0xe934Dc97E347C6aCef74364B50125bb8689c40ff = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 68}
]
