templateName = "MigrateToLiveness2"

safeAddressString = "FoundationOperationsSafe"

[addresses]
saferSafes = "0xA8447329e52F64AED2bFc9E7a2506F7D369f483a"
# currentLivenessModule is omitted - FoS has no existing liveness module

[livenessModule]
livenessResponsePeriod = "2592000"  # 30 days in seconds
fallbackOwner = "0xc2819DC788505Aac350142A7A707BF9D03E3Bd03"  # Security Council

[stateOverrides]
# Foundation Operations Safe
0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A = [
     {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 113}
]

