# example file

[[addresses]]
addr = "0x9679E26bf0C470521DE83Ad77BB1bf1e7312f739"
identifier = "DEPLOYER_EOA"
isContract = false

[[addresses]]
addr = "0xc0Da02939E1441F497fd74F78cE7Decb17B66529"
identifier = "COMPOUND_GOVERNOR_BRAVO"
isContract = true

[[addresses]]
addr = "0x316f9708bB98af7dA9c68C1C3b5e79039cD336E3"
identifier = "COMPOUND_CONFIGURATOR"
isContract = true

[[addresses]]
addr = "0x240B3bd6b95cE40497Aafd71aD4705d0345A33CD"
identifier = "SYSTEM_CONFIG_LOGIC"
isContract = true
