templateName = "GnosisSafeRotateSigner"

safeAddressString = "SecurityCouncil"

# Pete is an owner on the Sepolia Security Council Safe: 0xf64bc17485f0B4Ea5F06A96514182FC4cB561977.
ownerToRemove = "0x72e828fdB48Cac259CB60d03222774fBD7e5522C"
ownerToAdd = "0xC703d73DB3804662B81b260056d8518Ab54e984E"

[stateOverrides]
0xf64bc17485f0B4Ea5F06A96514182FC4cB561977 = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 64}
]
