# Jovian Betanet on u17
l2chains = [
    {name = "jovian-beta-0", chainId = 420110019},
    {name = "jovian-beta-1", chainId = 420110020}
]

# Addresses for this task can be found here: https://github.com/ethereum-optimism/devnets/pull/170/files
fallbackAddressesJsonPath = "src/tasks/sep/038-U17-op-betanets/addresses.json"
templateName = "OPCMUpgradeV500"
allowOverwrite = ["SuperchainConfig", "SuperchainConfigProxyAdmin"]

[[opcmUpgrades]]
chainId = 420110019
# Jovian prestate:
absolutePrestate = "0x03caa1871bb9fe7f9b11217c245c16e4ded33367df5b3ccb2c6d0a847a217d1b"  # prestates."1.8.0-rc.4" https://www.notion.so/oplabs/U17-2a1f153ee162804f94d0c10d0a1e1258
expectedValidationErrors = "PROXYA-10,SYSCON-140,DF-30,PDDG-DWETH-30,PDDG-130,PLDG-10"
# PROXYA-10: ProxyAdmin owner is not set to the Standard PAO multisig
# SYSCON-140: The SystemConfig.SuperchainConfig is not the standard one
# DF-30: DisputeGameFactory owner is not set to the Standard PAO multisig
# PDDG-DWETH-30: Permissioned dispute game delayed WETH owner mismatch
# PDDG-130: The PDDG Challenger is not the standard one
# PLDG-10: Permissionless dispute game implementation not found. Expected as it's a permissioned chain.

[[opcmUpgrades]]
chainId = 420110020
# Jovian prestate:
absolutePrestate = "0x03caa1871bb9fe7f9b11217c245c16e4ded33367df5b3ccb2c6d0a847a217d1b"  # prestates."1.8.0-rc.4" https://www.notion.so/oplabs/U17-2a1f153ee162804f94d0c10d0a1e1258
expectedValidationErrors = "PROXYA-10,SYSCON-140,DF-30,PDDG-DWETH-30,PDDG-130,PLDG-DWETH-30"
# PROXYA-10: ProxyAdmin owner is not set to the Standard PAO multisig
# SYSCON-140: The SystemConfig.SuperchainConfig is not the standard one
# DF-30: DisputeGameFactory owner is not set to the Standard PAO multisig
# PDDG-DWETH-30: The PDDG is not the standard one
# PDDG-130: The PDDG Challenger is not the standard one
# PLDG-DWETH-30: The PLDG is not the standard one

[addresses]
OPCM = "0xc69e4c24db479191676611a25d977203c3bdca62"  # Source: to add reference
StandardValidatorV500 = "0x757bfa3aaabce60112cee3239dcd05b5f6efae3a"  # Source: validator from OPCM above, can be checked on etherscan
SuperchainConfig = "0x1FdE152a794701A86B38f8f657E591C3c7979Cde"  # Source: https://github.com/ethereum-optimism/devnets/pull/170/files#diff-0c8aaa2fab40915fae70ed0b990ef55226c132d348477e314457d759961b5c59R7
SuperchainConfigProxyAdmin = "0xFf112a58983aD809EE998d6A7652988fC93228E8"  # Source: ProxyAdmin from the contract above https://sepolia.etherscan.io/address/0x1FdE152a794701A86B38f8f657E591C3c7979Cde#readProxyContract

[stateOverrides]
0xe934Dc97E347C6aCef74364B50125bb8689c40ff = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 47}
]
