# Jovian Betanet on u17
l2chains = [
    {name = "jovian-beta-0", chainId = 420110019},
    {name = "jovian-beta-1", chainId = 420110020}
]

# Addresses for this task can be found here: https://github.com/ethereum-optimism/devnets/pull/170/files
fallbackAddressesJsonPath = "src/tasks/sep/038-U17-op-betanets/addresses.json"
templateName = "OPCMUpgradeV500"
allowOverwrite = ["SuperchainConfig", "SuperchainConfigProxyAdmin"]

[[opcmUpgrades]]
chainId = 420110019
# Jovian prestate:
absolutePrestate = "0x03799051d2bfe459127d4597f469f535ff1bd2a6e1e2134443167620871c11f3"  # prestates."1.8.0-rc.3" https://github.com/ethereum-optimism/superchain-registry/blob/c9881d543174ff00b8f3a9ad3f31bf4630b9743b/validation/standard/standard-prestates.toml#L6
expectedValidationErrors = "PROXYA-10,SYSCON-140,DF-30,PDDG-DWETH-30,PDDG-VM-30,PDDG-130,PLDG-10"

[[opcmUpgrades]]
chainId = 420110020
# Jovian prestate:
absolutePrestate = "0x03799051d2bfe459127d4597f469f535ff1bd2a6e1e2134443167620871c11f3"  # prestates."1.8.0-rc.3" https://github.com/ethereum-optimism/superchain-registry/blob/c9881d543174ff00b8f3a9ad3f31bf4630b9743b/validation/standard/standard-prestates.toml#L6
expectedValidationErrors = "PROXYA-10,SYSCON-140,DF-30,PDDG-DWETH-30,PDDG-VM-30,PDDG-130,PLDG-DWETH-30,PLDG-VM-30"

[addresses]
OPCM = "0x6af7ece7d6506be573841b8cf29096638df5fc4f"  # Source: https://www.notion.so/oplabs/op-contracts-release-for-U17-Jovian-294f153ee16280b99539c5b6de67c72f?source=copy_link#295f153ee162800a84c7f37811ecf3ec
StandardValidatorV500 = "0x8ed9A48B40675acf9ec623aFc23DdB015Ae60df0"  # Source: cast call validator's from OPCM above
SuperchainConfig = "0x1FdE152a794701A86B38f8f657E591C3c7979Cde"  # Source: https://sepolia.etherscan.io/address/0x1FdE152a794701A86B38f8f657E591C3c7979Cde#readProxyContract
SuperchainConfigProxyAdmin = "0xFf112a58983aD809EE998d6A7652988fC93228E8"  # Source: cast call ProxyAdmin address from SuperchainConfig above https://sepolia.etherscan.io/address/0x1FdE152a794701A86B38f8f657E591C3c7979Cde#readProxyContract

[stateOverrides]
0xe934Dc97E347C6aCef74364B50125bb8689c40ff = [
    {key = "0x0000000000000000000000000000000000000000000000000000000000000005", value = 47}
]